# Generated by Django 5.2.9 on 2025-12-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('license_number', models.CharField(max_length=50)),
                ('license_expiry', models.DateField()),
                ('bus_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
