# Generated by Django 5.2.9 on 2025-12-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdrivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('bus_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='busdrivers.busdriver')),
            ],
        ),
    ]
